# Generated by Django 5.1.5 on 2025-02-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="role",
            new_name="user_type",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="po_file",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="slip_file",
        ),
        migrations.RemoveField(
            model_name="salerecord",
            name="status",
        ),
        migrations.AddField(
            model_name="salerecord",
            name="payment_slip",
            field=models.FileField(blank=True, null=True, upload_to="payment_slips/"),
        ),
        migrations.AddField(
            model_name="salerecord",
            name="po_document",
            field=models.FileField(blank=True, null=True, upload_to="po_documents/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="salerecord",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.product",
            ),
        ),
        migrations.AlterField(
            model_name="salerecord",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="salerecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.customer",
            ),
        ),
    ]
