# Generated by Django 5.1.5 on 2025-02-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_salerecord_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
