# Generated by Django 5.1.5 on 2025-02-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salerecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
